# instrucciones para travis para que haaga el sbuild

language: node_js
node_js: 
 - "12"
jdk:
 - oraclejdk8
addons:
 sonarcloud: true 
script:
 - sonar-scanner -Dsonar.login=$SONAR_TOKEN -Dsonar.organization=vanessatocasuche -Dsonar.projectKey=Calculadora -Dsonar.sources='./app' -X



#install:
#- 'npm install'